-- Schema for RF004
-- Generated by Architecture Owner Agent v1.0.0

CREATE TABLE IF NOT EXISTS oracles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL CHECK (type IN ('backend', 'frontend')),
    config JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,

    CONSTRAINT oracles_name_unique UNIQUE (name)
);

-- Indexes
CREATE INDEX idx_oracles_type ON oracles(type);
CREATE INDEX idx_oracles_created_at ON oracles(created_at DESC);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_oracles_updated_at
    BEFORE UPDATE ON oracles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Comments
COMMENT ON TABLE oracles IS 'Oracles store domain knowledge and configuration for generating solutions';
COMMENT ON COLUMN oracles.type IS 'Type of oracle: backend (APIs) or frontend (UI)';
COMMENT ON COLUMN oracles.config IS 'JSONB configuration for oracle behavior';
